/* eslint-disable */
require('./bars')
require('./cart')
require('./chevron-down')
require('./chevron-left')
require('./chevron-right')
require('./chevron-up')
require('./close')
require('./flag')
require('./heart-outline')
require('./heart')
require('./mobile')
require('./phone')
require('./reader')
require('./shopping-cart')
require('./theme4nuxt-logo')
require('./trash')
